"""The Resident: report drafting, Ask, and the Scribe (spec sections 10.1 to 10.5). Owner: Brandon.

Starts in MOCK mode. Real version: Mellea @generative functions with the requirements in 10.4/10.5.
Frames sent to /scribe/window are processed in memory only and NEVER written to disk or logged.
"""
import os
from uuid import uuid4

from fastapi import FastAPI, File, Form, UploadFile

from asclep_contracts import (
    AskAnswer,
    AskRequest,
    Citation,
    DraftReport,
    DraftReportRequest,
    ScribeObservation,
    ScribeWindowResult,
)

app = FastAPI(title="Asclep Resident")
MOCK = os.getenv("RESIDENT_MOCK", "1") == "1"


@app.get("/health")
def health():
    return {"status": "ok", "mock": MOCK}


@app.post("/draft-report", response_model=DraftReport)
def draft_report(req: DraftReportRequest) -> DraftReport:
    f = req.finding
    body = (
        "## AI finding (unverified)\n"
        f"{f.label}, model confidence {f.confidence:.2f} ({f.model_name}).\n\n"
        "## Relevant patient context\n"
        + "".join(f"- {c.text} [[obj:{c.object_type}:{c.id}]]\n" for c in req.patient_context[:6])
        + "\n_Draft generated by Asclep. Requires physician review._"
    )
    cites = [Citation(object_type=c.object_type, id=c.id) for c in req.patient_context[:6]]
    return DraftReport(body_md=body, citations=cites, locked_check_passed=True)


@app.post("/ask", response_model=AskAnswer)
def ask(req: AskRequest) -> AskAnswer:
    return AskAnswer(
        answer_md="(mock) The Resident is not wired yet. Real answers cite every fact.",
        citations=[], conversation_id=req.conversation_id or str(uuid4()), verified=False,
    )


@app.post("/scribe/window", response_model=ScribeWindowResult)
async def scribe_window(
    session_id: str = Form(...),
    window_start: str = Form(...),
    window_end: str = Form(...),
    frames: list[UploadFile] = File(...),
) -> ScribeWindowResult:
    # PRIVACY: read frames into memory only; never save, never log (spec 10.5 guarantee 2).
    _ = [await f.read() for f in frames]
    del _
    return ScribeWindowResult(
        session_id=session_id, window_start=window_start, window_end=window_end,
        observations=[ScribeObservation(t=window_start, category="mobility",
                                        text="(mock) Walked to the chair without assistance", confidence=0.8)],
        people_in_frame=1,
    )
