"""Job 1: the pathology report draft (spec 10.1). Owner: Brandon.

The locked-value guarantee: the model never writes the finding section, and anywhere it refers to the finding
it writes {{FINDING.*}} placeholders that the server fills in. It returns cited bullets as JSON; the server
assembles the fixed headings, checks every requirement, retries with the problems fed back, and after
LOOP_BUDGET failures returns a template-only report with locked_check_passed=False.
"""
import json

from pydantic import BaseModel

from app import llm
from app.validate import CITE, locked_values_intact, no_dosing, numbers_grounded
from asclep_contracts import Citation, DraftReport, DraftReportRequest

FOOTER = "_Draft generated by Asclep. Requires physician review._"

SYSTEM = """You draft pathology report sections for a physician to review. You explain; you never decide.
Rules:
- Use only the patient records given. Every bullet cites the ids of the records it rests on.
- Never write a subtype name, label, confidence, or score. Refer to the AI finding only with the placeholders
  {{FINDING.LABEL}}, {{FINDING.CONFIDENCE}}, {{FINDING.MODEL}}, {{FINDING.SCORES}}.
- Copy numbers exactly as they appear in the records; never compute new ones.
- context: 3 to 6 bullets of the patient context most relevant to this finding.
- conflicts: records that disagree or are missing (e.g. no prior imaging on file); cite what you can.
- considerations: general next steps phrased as considerations (e.g. molecular testing is commonly
  considered). No doses, routes, frequencies, or definitive treatment plans. No citations needed.
- Short plain sentences."""


class Bullet(BaseModel):
    text: str
    cite: list[str]  # ids of the given records


class ReportSections(BaseModel):
    context: list[Bullet]
    conflicts: list[Bullet]
    considerations: list[str]


def fill(text: str, req: DraftReportRequest) -> str:
    f = req.finding
    scores = ", ".join(f"{k} {v:.2f}" for k, v in f.class_scores.items())
    return (text.replace("{{FINDING.LABEL}}", f.label).replace("{{FINDING.CONFIDENCE}}", f"{f.confidence:.2f}")
            .replace("{{FINDING.MODEL}}", f"{f.model_name} {f.model_version}").replace("{{FINDING.SCORES}}", scores))


def finding_section(req: DraftReportRequest) -> str:
    flags = f" Flags: {', '.join(req.finding.flags)}." if req.finding.flags else ""
    return ("## AI finding (unverified)\n"
            "- {{FINDING.LABEL}}, model confidence {{FINDING.CONFIDENCE}} ({{FINDING.MODEL}}); class scores "
            "{{FINDING.SCORES}}. The heatmap marks the tissue regions that drove this score." + flags
            + f" [[obj:Finding:{req.finding.finding_id}]]\n")


def cite_tokens(ids: list[str], types: dict[str, str]) -> str:
    return "".join(f" [[obj:{types[i.strip().lower()]}:{i.strip()}]]" for i in ids)


def assemble(req: DraftReportRequest, s: ReportSections) -> str:
    types = {str(c.id).lower(): c.object_type for c in req.patient_context}
    lines = [finding_section(req), "## Relevant patient context"]
    lines += [f"- {b.text}{cite_tokens(b.cite, types)}" for b in s.context]
    lines += ["", "## Conflicts or gaps"]
    lines += [f"- {b.text}{cite_tokens(b.cite, types)}" for b in s.conflicts] or ["- None found in the records given."]
    lines += ["", "## Considerations for the physician"] + [f"- {c}" for c in s.considerations]
    return "\n".join(lines + ["", FOOTER])


def template_only(req: DraftReportRequest, passed: bool, attempts: int) -> DraftReport:
    """No model text at all: the finding and the context records verbatim, each cited."""
    ctx = req.patient_context[:6]
    body = "\n".join([finding_section(req), "## Relevant patient context"]
                     + [f"- {c.text} [[obj:{c.object_type}:{c.id}]]" for c in ctx] + ["", FOOTER])
    return finalize(req, body, passed, attempts)


def finalize(req: DraftReportRequest, body: str, passed: bool, attempts: int) -> DraftReport:
    body = fill(body, req)
    seen, cites = set(), []
    for type_, oid in CITE.findall(body):
        if oid.lower() not in seen:
            seen.add(oid.lower())
            cites.append(Citation(object_type=type_, id=oid))
    return DraftReport(body_md=body, citations=cites, locked_check_passed=passed, attempts=attempts)


def problems(req: DraftReportRequest, s: ReportSections) -> list[str]:
    f = req.finding
    allowed = {str(c.id).lower() for c in req.patient_context}
    model_text = "\n".join([b.text for b in s.context + s.conflicts] + s.considerations)
    sources = " ".join(c.text for c in req.patient_context) + json.dumps(req.locked_facts, default=str)
    out = locked_values_intact(model_text, f.label, f.class_scores)
    out += [f"Citation id '{i}' is not one of the record ids given. Cite only those ids."
            for b in s.context + s.conflicts for i in b.cite if i.strip().lower() not in allowed]
    out += numbers_grounded(model_text, sources) + no_dosing(model_text)
    if not 3 <= len(s.context) <= 6:
        out.append(f"Give 3 to 6 context bullets, not {len(s.context)}.")
    out += [f'Cite a record for: "{b.text[:60]}"' for b in s.context if not b.cite]
    return out


def prompt(req: DraftReportRequest, feedback: list[str]) -> str:
    records = "\n".join(f"- id={c.id} type={c.object_type}: {c.text}" for c in req.patient_context)
    text = (f"Patient records:\n{records or '- (none)'}\n\nKey lab facts (locked, copy exactly):\n"
            f"{json.dumps(req.locked_facts, default=str)}\n\nFinding flags: {req.finding.flags or 'none'}")
    if feedback:
        text += "\n\nYour last draft failed these checks. Fix every one:\n" + "\n".join(f"- {p}" for p in feedback)
    return text


def draft(req: DraftReportRequest) -> DraftReport:
    if llm.MOCK:
        return template_only(req, passed=True, attempts=1)
    feedback: list[str] = []
    for attempt in range(1, llm.LOOP_BUDGET + 1):
        try:
            r = llm.client().messages.parse(model=llm.MODEL, max_tokens=8000, system=SYSTEM,
                                            messages=[{"role": "user", "content": prompt(req, feedback)}],
                                            output_format=ReportSections)
            sections = r.parsed_output
        except Exception as exc:  # API down, refusal, unparsable: count it as a failed attempt
            feedback, sections = [f"The reply could not be used ({type(exc).__name__}). Reply with the JSON."], None
        if sections is None:
            continue
        feedback = problems(req, sections)
        if not feedback:
            return finalize(req, assemble(req, sections), passed=True, attempts=attempt)
    return template_only(req, passed=False, attempts=llm.LOOP_BUDGET)
